MC-39996: Add support for Composer 2
magento-commerce/inventory-composer-installer pull request #6
Opened 2020-12-17 17:20 UTC by Rrego6

- Added composer2 support

2020-12-17 19:10 UTC, fascinosum requested changes

2020-12-17 19:10 UTC, fascinosum commented on composer.json
> +    "version": "1.1.1",
I would recommend to increase a minor version

2020-12-17 19:10 UTC, fascinosum commented on src/Plugin.php
> +    public function deactivate(Composer $composer, IOInterface $io)
please add `@inheritDoc`

2020-12-17 19:21 UTC, Rrego6 commented on composer.json
> +    "version": "1.1.1",
Fixed

2020-12-17 19:22 UTC, Rrego6 commented on src/Plugin.php
> +    public function deactivate(Composer $composer, IOInterface $io)
Fixed

2020-12-17 19:26 UTC, fascinosum approved these changes

2020-12-17 19:28 UTC, sidolov approved these changes

2020-12-17 19:55 UTC, merged

2020-12-21 22:36 UTC, hostep commented
Great!

But please next time take a look at the open PR's on the repo and try to acknowledge the community members who already put time and effort into this (#3, #4), thanks!

2021-01-19 22:32 UTC, fascinosum commented
Hi @hostep,
sorry we missed them. There were a bunch of projects we needed to upgrade and test in order to have Composer 2 for Magento 2.4.2 in time.
This won't be the case if we regularly process PRs for this repo. @sidolov do we have a process in place?